### ISSUE TITLE
Fibonacci number using recursion

### ISSUE THREAD

**Issue by niteshbharti005101** [snh3003/CS-Algorithms-and-Programs-that-every-programmer-should-know#1]
Fibonacci number using recursion

**Comment by niteshbharti005101** [comment]
def fibo(n):
    if(n==1):
        return 0
    elif(n==2):
        return 1
    else:
        return fibo(n-1) + fibo(n-2)
    
num = int(input("Enter the number = "))
print(fibo(num))

**Comment by snh3003** [comment]
Pull merged
Closing the issue
